#-*- mode: ruby -*-

source 'https://rubygems.org'

gem 'leafy-metrics', :path => '../leafy-metrics'
gem 'leafy-health', :path => '../leafy-health'
gem 'leafy-logger', :path => '../leafy-logger'

gemspec

# vim: syntax=Ruby
