# this is a generated file, to avoid over-writing it just delete this comment
require 'jar_dependencies'

require_jar( 'com.fasterxml.jackson.core', 'jackson-databind', '2.5.1' )
require_jar( 'io.dropwizard', 'dropwizard-jackson', '0.8.0-rc5' )
require_jar( 'io.dropwizard', 'dropwizard-util', '0.8.0-rc5' )
require_jar( 'com.fasterxml.jackson.module', 'jackson-module-afterburner', '2.5.1' )
require_jar( 'com.fasterxml.jackson.datatype', 'jackson-datatype-guava', '2.5.1' )
require_jar( 'com.google.code.findbugs', 'jsr305', '3.0.0' )
require_jar( 'org.slf4j', 'log4j-over-slf4j', '1.7.10' )
require_jar( 'ch.qos.logback', 'logback-core', '1.1.2' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-core', '2.5.1' )
require_jar( 'org.slf4j', 'jul-to-slf4j', '1.7.10' )
require_jar( 'org.glassfish', 'javax.el', '3.0.0' )
require_jar( 'com.fasterxml.jackson.datatype', 'jackson-datatype-jdk7', '2.5.1' )
require_jar( 'io.dropwizard', 'dropwizard-validation', '0.8.0-rc5' )
require_jar( 'javax.validation', 'validation-api', '1.1.0.Final' )
require_jar( 'ch.qos.logback', 'logback-classic', '1.1.2' )
require_jar( 'org.apache.commons', 'commons-lang3', '3.3.2' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-annotations', '2.5.0' )
require_jar( 'com.fasterxml.jackson.datatype', 'jackson-datatype-joda', '2.5.1' )
require_jar( 'org.eclipse.jetty', 'jetty-util', '9.2.9.v20150224' )
require_jar( 'com.fasterxml.jackson.dataformat', 'jackson-dataformat-yaml', '2.5.1' )
require_jar( 'com.fasterxml', 'classmate', '1.0.0' )
require_jar( 'org.slf4j', 'slf4j-api', '1.7.10' )
require_jar( 'io.dropwizard', 'dropwizard-configuration', '0.8.0-rc5' )
require_jar( 'org.jboss.logging', 'jboss-logging', '3.1.3.GA' )
require_jar( 'io.dropwizard.metrics', 'metrics-core', '3.1.0' )
require_jar( 'org.slf4j', 'jcl-over-slf4j', '1.7.10' )
require_jar( 'org.hibernate', 'hibernate-validator', '5.1.3.Final' )
require_jar( 'io.dropwizard', 'dropwizard-logging', '0.8.0-rc5' )
require_jar( 'io.dropwizard.metrics', 'metrics-logback', '3.1.0' )
require_jar( 'com.google.guava', 'guava', '18.0' )
